<?php

/**
 * @file
 * Adds jquery migrate plugin.
 */

/**
 * Implements hook_menu().
 */
function jquery_migrate_menu() {
  $items = array();

  $items['admin/config/user-interface/jquery-migrate'] = array(
    'title' => 'jQuery migrate',
    'description' => 'Change jquery migrate configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jquery_migrate_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'jquery_migrate.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function jquery_migrate_init() {
  $front_values = array(1, 2);
  $admin_values = array(0, 2);
  $where = variable_get('jquery_migrate_activate_on', 2);

  if(drupal_is_front_page() && in_array($where, $front_values)) {
    jquery_migrate_add_library();
  }
  else if(path_is_admin(current_path()) && in_array($where, $admin_values)) {
    jquery_migrate_add_library();
  }
}

/**
 * Adds jquery migrate plugin.
 * http://code.jquery.com/
 */
function jquery_migrate_add_library() {
  $options = array('type' => 'external', 'weight' => -17);
  drupal_add_js('http://code.jquery.com/jquery-migrate-1.2.1.min.js', $options);
}
